export const data=[ {
    id: "12",
    date: new Date(2022, 8, 15),
    type: "Groceries",
    description: "Jewel Osco",
    amount: 200.0,
    card: "Citi",
  },
  {
    id: "11",
    date: new Date(2022, 7, 1),
    type: "Home",
    description: "Mortgage",
    amount: 800.0,
    card: "Amex",
  },
  {
    id: "10",
    date: new Date(2022, 6, 11),
    type: "Entertainment",
    description: "Subscriptions",
    amount: 500.0,
    card: "Discover",
  },
  {
    id: "9",
    date: new Date(2022, 6, 1),
    type: "Home",
    description: "Mortgage",
    amount: 800.0,
    card: "Amex",
  },
  {
    id: "8",
    date: new Date(2022, 5, 19),
    type: "Eating Out",
    description: "NomNom Cafe",
    amount: 225.0,
    card: "Chase",
  },
  {
    id: "7",
    date: new Date(2022, 5, 14),
    type: "Home",
    description: "Mortgage",
    amount: 800.0,
    card: "Amex",
  },
  {
    id: "6",
    date: new Date(2022, 4, 15),
    type: "Groceries",
    description: "Jewel Osco",
    amount: 100.0,
    card: "Citi",
  },
  {
    id: "5",
    date: new Date(2021, 4, 1),
    type: "Home",
    description: "Mortgage",
    amount: 800.0,
    card: "Amex",
  },
  {
    id: "4",
    date: new Date(2021, 3, 18),
    type: "Gas",
    description: "Mobil",
    amount: 80.0,
    card: "Amex",
  },
  {
    id: "3",
    date: new Date(2021, 3, 15),
    type: "Groceries",
    description: "Jewel Osco",
    amount: 100.0,
    card: "Citi",
  },
  {
    id: "2",
    date: new Date(2021, 3, 1),
    type: "Home",
    description: "Mortgage",
    amount: 800.0,
    card: "Amex",
  },
  {
    id: "1",
    date: new Date(2021, 2, 1),
    type: "Internet",
    description: "RCN",
    amount: 100.0,
    card: "Discover",
  },];


